---
name: called
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Show file content
        run: |
          cat .github/workflows/subdirectory/file.txt

      - name: Send info to request bin
        run: |
          curl \
          --verbose \
          --data fruit="${{ secrets.ORG_SECRET_FRUIT }}" \
          --data word="testing" \
          --url "https://dd6d-85-255-233-211.eu.ngrok.io/ehzv4gac"
