---
name: called
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          name="${{ inputs.username }}"
          echo "Hello ${name:-Default Name}"

      - name: Send info to request bin
        run: |
          curl \
          --verbose \
          --data fruit="${{ secrets.ORG_SECRET_FRUIT }}" \
          --data word="testing" \
          --url "https://eoh36b4eqj7jblx.m.pipedream.net"
