---
name: called
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      mysecret:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          name=${{ inputs.username }}
          echo "Hello ${name:-Default Name}"

      - name: Output environment
        run: env
